/* ═══ ITEM ICONS — per-item emoji for visual flair ═══ */
const ITEM_ICONS = {
  // Fruits
  apple:"🍎",apples:"🍎",banana:"🍌",bananas:"🍌",orange:"🍊",oranges:"🍊",mandarin:"🍊",clementine:"🍊",
  lemon:"🍋",lemons:"🍋",lime:"🍋‍🟩",limes:"🍋‍🟩",grape:"🍇",grapes:"🍇",watermelon:"🍉",tarbooz:"🍉",
  melon:"🍈",cantaloupe:"🍈",honeydew:"🍈",strawberry:"🍓",strawberries:"🍓",blueberry:"🫐",blueberries:"🫐",
  cherry:"🍒",cherries:"🍒",peach:"🍑",peaches:"🍑",nectarine:"🍑",pear:"🍐",pears:"🍐",pineapple:"🍍",
  mango:"🥭",mangoes:"🥭",aam:"🥭",kiwi:"🥝",coconut:"🥥",nariyal:"🥥",pomegranate:"🍎",anaar:"🍎",
  papaya:"🥭",guava:"🍐",amrud:"🍐",raspberry:"🍓",raspberries:"🍓",blackberry:"🫐",blackberries:"🫐",
  cranberry:"🍒",cranberries:"🍒",apricot:"🍑",plum:"🫐",plums:"🫐",fig:"🍇",figs:"🍇",anjeer:"🍇",
  date:"🌴",dates:"🌴",khajoor:"🌴",lychee:"🍑",litchi:"🍑",jackfruit:"🍈",kathal:"🍈",fruit:"🍎",fruits:"🍎",
  // Vegetables
  tomato:"🍅",tomatoes:"🍅",carrot:"🥕",carrots:"🥕",potato:"🥔",potatoes:"🥔",
  "sweet potato":"🍠","sweet potatoes":"🍠",aloo:"🥔",corn:"🌽","corn on the cob":"🌽",bhutta:"🌽",
  broccoli:"🥦",cauliflower:"🥦",gobi:"🥦",lettuce:"🥬",romaine:"🥬",spinach:"🥬",kale:"🥬",
  arugula:"🥬","spring mix":"🥬","mixed greens":"🥬",greens:"🥬",avocado:"🥑",avocados:"🥑",
  cucumber:"🥒",cucumbers:"🥒",zucchini:"🥒",pepper:"🫑",peppers:"🫑","bell pepper":"🫑",
  jalapeno:"🌶️",serrano:"🌶️",habanero:"🌶️",poblano:"🌶️","hot pepper":"🌶️",
  eggplant:"🍆",baingan:"🍆",mushroom:"🍄",mushrooms:"🍄",portobello:"🍄",shiitake:"🍄",cremini:"🍄",
  onion:"🧅",onions:"🧅","red onion":"🧅","green onion":"🧅",scallion:"🧅",scallions:"🧅",shallot:"🧅",shallots:"🧅",
  garlic:"🧄",ginger:"🫚","turmeric root":"🫚",peanuts:"🥜",peanut:"🥜",moongfali:"🥜",
  beans:"🫘","green beans":"🫘","brussels sprouts":"🥦",cabbage:"🥬","bok choy":"🥬",
  squash:"🎃","butternut squash":"🎃",pumpkin:"🎃",kaddu:"🎃",celery:"🥬",radish:"🥕",
  beet:"🥕",beets:"🥕",turnip:"🥕",asparagus:"🌿",artichoke:"🌿",okra:"🌿",bhindi:"🌿",
  "snap peas":"🫛","snow peas":"🫛",yam:"🍠",yams:"🍠",
  vegetable:"🥬",vegetables:"🥬",veggies:"🥬",sabzi:"🥬",salad:"🥗",
  // Herbs
  cilantro:"🌿",dhaniya:"🌿",basil:"🌿",tulsi:"🌿",mint:"🌿",pudina:"🌿",parsley:"🌿",
  dill:"🌿",suva:"🌿",herbs:"🌿","fresh herbs":"🌿",
  "curry leaves":"🍃","kadi patta":"🍃",methi:"🍃","fenugreek leaves":"🍃",drumstick:"🌿",moringa:"🌿",sahjan:"🌿",
  // Dairy & Eggs
  milk:"🥛","whole milk":"🥛","2% milk":"🥛","skim milk":"🥛",buttermilk:"🥛",chaas:"🥛",
  cheese:"🧀","shredded cheese":"🧀","sliced cheese":"🧀","string cheese":"🧀",mozzarella:"🧀",parmesan:"🧀",
  cheddar:"🧀",swiss:"🧀",provolone:"🧀",gouda:"🧀",brie:"🧀",feta:"🧀",ricotta:"🧀",
  "goat cheese":"🧀","cream cheese":"🧀","cottage cheese":"🧀",queso:"🧀",paneer:"🧀",
  yogurt:"🥛","greek yogurt":"🥛",yoghurt:"🥛",dahi:"🥛",
  butter:"🧈","unsalted butter":"🧈","salted butter":"🧈",margarine:"🧈",makhan:"🧈",ghee:"🧈",
  cream:"🥛","heavy cream":"🥛","whipping cream":"🥛","half and half":"🥛","sour cream":"🥛",malai:"🥛",
  egg:"🥚",eggs:"🥚","egg whites":"🥚","dozen eggs":"🥚",anda:"🥚",
  curd:"🥛",khoya:"🥛",mawa:"🥛",creamer:"🥛","coffee creamer":"🥛",lassi:"🥛",
  // Meat & Poultry
  chicken:"🍗","chicken breast":"🍗","chicken thigh":"🍗","chicken thighs":"🍗","chicken wings":"🍗",
  "chicken legs":"🍗","chicken drumsticks":"🍗","whole chicken":"🍗","rotisserie chicken":"🍗",
  "chicken tender":"🍗","chicken tenders":"🍗",murgh:"🍗",
  beef:"🥩","ground beef":"🥩",steak:"🥩",sirloin:"🥩",ribeye:"🥩","filet mignon":"🥩","flank steak":"🥩",
  "chuck roast":"🥩",roast:"🥩","pot roast":"🥩",brisket:"🥩","beef stew":"🥩",
  pork:"🥩","pork chop":"🥩","pork chops":"🥩","pork loin":"🥩","pork tenderloin":"🥩","pork belly":"🥩",
  bacon:"🥓","turkey bacon":"🥓","canadian bacon":"🥓",
  sausage:"🌭",sausages:"🌭","italian sausage":"🌭",bratwurst:"🌭",kielbasa:"🌭",chorizo:"🌭",
  turkey:"🦃","turkey breast":"🦃","ground turkey":"🦃",duck:"🦆",
  lamb:"🍖","lamb chop":"🍖","lamb chops":"🍖","lamb leg":"🍖","rack of lamb":"🍖",keema:"🍖",gosht:"🍖",
  veal:"🥩",bison:"🥩",venison:"🥩",meatball:"🍖",meatballs:"🍖",patties:"🍔","burger patties":"🍔",
  ham:"🍖","spiral ham":"🍖",ribs:"🍖","baby back ribs":"🍖","spare ribs":"🍖",
  "hot dog":"🌭","hot dogs":"🌭",
  // Seafood
  shrimp:"🦐",prawns:"🦐",jhinga:"🦐",salmon:"🐟","salmon fillet":"🐟","smoked salmon":"🐟",lox:"🐟",
  tuna:"🐟","ahi tuna":"🐟","tuna steak":"🐟","canned tuna":"🐟",
  fish:"🐟","fish fillet":"🐟","fish sticks":"🐟",machhi:"🐟",cod:"🐟",tilapia:"🐟",halibut:"🐟",
  "mahi mahi":"🐟",swordfish:"🐟",trout:"🐟",catfish:"🐟",bass:"🐟",snapper:"🐟",pomfret:"🐟",rohu:"🐟",surmai:"🐟",
  crab:"🦀","crab legs":"🦀","crab meat":"🦀",lobster:"🦞","lobster tail":"🦞",
  scallop:"🐚",scallops:"🐚",clam:"🐚",clams:"🐚",mussel:"🐚",mussels:"🐚",oyster:"🦪",oysters:"🦪",
  squid:"🦑",calamari:"🦑",octopus:"🐙",anchovies:"🐟",sardines:"🐟",sushi:"🍣",sashimi:"🍣",
  // Bakery
  bread:"🍞","white bread":"🍞","wheat bread":"🍞","whole wheat bread":"🍞","multigrain bread":"🍞",sourdough:"🍞","rye bread":"🍞",
  bagel:"🥯",bagels:"🥯","everything bagel":"🥯",croissant:"🥐",croissants:"🥐",
  muffin:"🧁",muffins:"🧁","blueberry muffin":"🧁",
  tortilla:"🫓",tortillas:"🫓","flour tortilla":"🫓","corn tortilla":"🫓",wrap:"🫓",wraps:"🫓",
  pita:"🫓","pita bread":"🫓",naan:"🫓",roti:"🫓",chapati:"🫓",paratha:"🫓",puri:"🫓",bhatura:"🫓",kulcha:"🫓",flatbread:"🫓",
  bun:"🍞",buns:"🍞","hamburger bun":"🍔","hot dog bun":"🌭",brioche:"🍞",pav:"🍞",
  roll:"🥖",rolls:"🥖","dinner rolls":"🥖",baguette:"🥖",ciabatta:"🥖",focaccia:"🥖",cornbread:"🍞",
  "english muffin":"🍞","english muffins":"🍞",
  cake:"🎂","birthday cake":"🎂",cupcake:"🧁",cupcakes:"🧁",pie:"🥧","pie crust":"🥧",
  cookie:"🍪",cookies:"🍪",brownie:"🍫",brownies:"🍫",
  donut:"🍩",donuts:"🍩",doughnut:"🍩",doughnuts:"🍩",
  pastry:"🥐",pastries:"🥐",scone:"🥐",scones:"🥐","cinnamon roll":"🍩","cinnamon rolls":"🍩",
  cracker:"🍘",crackers:"🍘","graham crackers":"🍘",rusks:"🍘",khari:"🍘",mathri:"🍘",
  pancakes:"🥞",waffle:"🧇",waffles:"🧇",pretzel:"🥨",pretzels:"🥨",
  // Deli
  "lunch meat":"🥩","deli meat":"🥩","sliced turkey":"🥩","sliced ham":"🥩","sliced chicken":"🥩",
  salami:"🥩",pepperoni:"🥩",prosciutto:"🥩",mortadella:"🥩",bologna:"🥩",pastrami:"🥩",
  hummus:"🫘",guacamole:"🥑","pico de gallo":"🍅",
  "prepared salad":"🥗","potato salad":"🥗",coleslaw:"🥗","macaroni salad":"🥗",
  rotisserie:"🍗","deli sandwich":"🥪",
  olive:"🫒",olives:"🫒",pickle:"🥒",pickles:"🥒",pickled:"🥒",achar:"🥒",charcuterie:"🥩",
  // Frozen
  "ice cream":"🍦",gelato:"🍨",sorbet:"🍧",kulfi:"🍦","frozen yogurt":"🍦",popsicle:"🍧",popsicles:"🍧",
  "frozen pizza":"🍕","frozen meal":"🍱","frozen meals":"🍱","frozen dinner":"🍱","tv dinner":"🍱",
  "frozen vegetables":"🥦","frozen veggies":"🥦","frozen fruit":"🍓","frozen berries":"🫐",
  "frozen chicken":"🍗","frozen shrimp":"🦐","frozen fish":"🐟",
  "frozen waffles":"🧇",eggo:"🧇","tater tots":"🥔","french fries":"🍟","frozen fries":"🍟","hash browns":"🥔",
  "pizza rolls":"🍕","hot pockets":"🌯","pot pie":"🥧",
  "frozen burrito":"🌯","frozen burritos":"🌯",ice:"🧊","ice cubes":"🧊",
  "frozen dumplings":"🥟",dumplings:"🥟",gyoza:"🥟",samosa:"🥟",samosas:"🥟",
  "frozen paratha":"🫓","frozen naan":"🫓","cool whip":"🍦","whipped topping":"🍦",
  // Pantry & Grains
  rice:"🍚","white rice":"🍚","brown rice":"🍚",basmati:"🍚","basmati rice":"🍚","jasmine rice":"🍚",chawal:"🍚",
  pasta:"🍝",spaghetti:"🍝",penne:"🍝",fusilli:"🍝",rigatoni:"🍝",macaroni:"🍝",linguine:"🍝",
  fettuccine:"🍝",lasagna:"🍝","angel hair":"🍝",
  noodles:"🍜",ramen:"🍜",udon:"🍜",soba:"🍜","rice noodles":"🍜","egg noodles":"🍜",
  "lo mein":"🍜",maggi:"🍜",sevai:"🍜",vermicelli:"🍜",seviyan:"🍜",
  flour:"🌾","all purpose flour":"🌾",maida:"🌾","bread flour":"🌾","almond flour":"🌾",
  "coconut flour":"🌾","whole wheat flour":"🌾",atta:"🌾",besan:"🌾","gram flour":"🌾",
  "rice flour":"🌾","ragi flour":"🌾","jowar flour":"🌾",
  sugar:"🍬","brown sugar":"🍬","powdered sugar":"🍬",shakkar:"🍬",gur:"🍯",jaggery:"🍯",mishri:"🍬",
  honey:"🍯",shahad:"🍯","maple syrup":"🍁",agave:"🍯",molasses:"🍯",
  oats:"🥣",oatmeal:"🥣",granola:"🥣",muesli:"🥣",daliya:"🥣",dalia:"🥣",cereal:"🥣",cheerios:"🥣",cornflakes:"🥣",
  "black beans":"🫘","kidney beans":"🫘",rajma:"🫘","pinto beans":"🫘","refried beans":"🫘",
  chickpeas:"🫘",chole:"🫘",chana:"🫘",garbanzo:"🫘",
  lentils:"🫘",dal:"🫘","moong dal":"🫘","toor dal":"🫘","masoor dal":"🫘","urad dal":"🫘","chana dal":"🫘",
  "canned tomatoes":"🥫","diced tomatoes":"🥫","crushed tomatoes":"🥫","tomato paste":"🥫",
  "tomato sauce":"🥫",marinara:"🥫","canned corn":"🥫","canned beans":"🥫","canned soup":"🥫",
  broth:"🥣",stock:"🥣","chicken broth":"🥣","chicken stock":"🥣","beef broth":"🥣","vegetable broth":"🥣","bone broth":"🥣",
  soup:"🍲","ramen packet":"🍜",
  quinoa:"🌾",couscous:"🌾",bulgur:"🌾",farro:"🌾",barley:"🌾",polenta:"🌾",grits:"🌾",
  poha:"🌾","flattened rice":"🌾","puffed rice":"🌾",murmura:"🌾",breadcrumbs:"🍞",panko:"🍞",
  "coconut milk":"🥥","evaporated milk":"🥛","condensed milk":"🥛",
  nuts:"🥜",almonds:"🥜",badam:"🥜",cashews:"🥜",kaju:"🥜",walnuts:"🥜",akhrot:"🥜",
  pecans:"🥜",pistachios:"🥜",pista:"🥜",macadamia:"🥜","mixed nuts":"🥜",
  "peanut butter":"🥜","almond butter":"🥜",nutella:"🍫",tahini:"🥜",
  jelly:"🍇",jam:"🍓",preserves:"🍓",marmalade:"🍊",
  tofu:"🧊",tempeh:"🧊",seitan:"🧊",ravioli:"🥟",tortellini:"🥟",
  "baking soda":"🧂","baking powder":"🧂",yeast:"🍞",cornstarch:"🌽",
  vanilla:"🌸","vanilla extract":"🌸","cocoa powder":"🍫",
  "protein powder":"💪","protein bar":"💪","protein bars":"💪",
  "chia seeds":"🌱","flax seeds":"🌱",alsi:"🌱","sunflower seeds":"🌻","pumpkin seeds":"🎃",
  "sesame seeds":"🌱",til:"🌱",
  papad:"🫓",appalam:"🫓",sev:"🍘",bhujia:"🍘",namkeen:"🍘",
  "idli mix":"🍚","dosa mix":"🍚","upma mix":"🍚",khichdi:"🍚",rava:"🌾",suji:"🌾",semolina:"🌾",
  // Snacks
  chips:"🍟","potato chips":"🍟","tortilla chips":"🍟","corn chips":"🍟","pita chips":"🍟","veggie chips":"🍟",
  popcorn:"🍿","microwave popcorn":"🍿",
  candy:"🍬",chocolate:"🍫","chocolate bar":"🍫","m&ms":"🍬",skittles:"🍬",
  "gummy bears":"🍬","gummy candy":"🍬","gummy worms":"🍬",
  "trail mix":"🥜","granola bar":"🥜","granola bars":"🥜","energy bar":"🥜","energy bars":"🥜",
  "fruit snack":"🍇","fruit snacks":"🍇","dried fruit":"🍇",raisins:"🍇","dried mango":"🥭",
  "rice cakes":"🍘","rice cake":"🍘",seaweed:"🌿","seaweed snack":"🌿",nori:"🌿",
  pudding:"🍮",jello:"🍮","fruit cup":"🍑",
  salsa:"🌶️","queso dip":"🧀","bean dip":"🫘",
  murukku:"🍘",chakli:"🍘",chivda:"🍘",khakhra:"🍘",
  cheetos:"🧀",doritos:"🍟","cheese puffs":"🧀","cheese crackers":"🍘",goldfish:"🐟",
  "beef jerky":"🥩","slim jim":"🥩",
  // Condiments & Spices
  ketchup:"🍅",mustard:"🌭","yellow mustard":"🌭","dijon mustard":"🌭",
  mayo:"🥚",mayonnaise:"🥚",
  "hot sauce":"🌶️",sriracha:"🌶️",tabasco:"🌶️",gochujang:"🌶️",sambal:"🌶️",
  "soy sauce":"🥢",tamari:"🥢","fish sauce":"🐟","oyster sauce":"🦪",hoisin:"🥢",teriyaki:"🥢",
  vinegar:"🫙","white vinegar":"🫙","apple cider vinegar":"🍎","balsamic vinegar":"🫙","rice vinegar":"🫙",
  oil:"🫒","olive oil":"🫒","extra virgin olive oil":"🫒","vegetable oil":"🫙","canola oil":"🫙",
  "coconut oil":"🥥","avocado oil":"🥑","sesame oil":"🫙","mustard oil":"🫙",
  "salad dressing":"🥗",ranch:"🥗","italian dressing":"🥗","caesar dressing":"🥗",vinaigrette:"🥗",
  "bbq sauce":"🍖","barbecue sauce":"🍖","steak sauce":"🥩",
  relish:"🥒",chutney:"🌿","cranberry sauce":"🍒",applesauce:"🍎",
  salt:"🧂","sea salt":"🧂","kosher salt":"🧂","pink salt":"🧂","sendha namak":"🧂","kala namak":"🧂","black salt":"🧂",
  "black pepper":"🫚","white pepper":"🫚","red pepper flakes":"🌶️",cayenne:"🌶️",
  cumin:"🫙",jeera:"🫙",turmeric:"🫙",haldi:"🫙",cinnamon:"🫙",dalchini:"🫙",paprika:"🌶️","smoked paprika":"🌶️",
  "chili powder":"🌶️","lal mirch":"🌶️","garlic powder":"🧄","onion powder":"🧅",
  oregano:"🌿","bay leaves":"🍃","tej patta":"🍃","curry powder":"🫙",
  "garam masala":"🫙","chaat masala":"🫙","pav bhaji masala":"🫙","biryani masala":"🫙",
  "kitchen king masala":"🫙","sambhar masala":"🫙",
  hing:"🫙",asafoetida:"🫙",ajwain:"🫙","carom seeds":"🫙",
  "fennel seeds":"🌱",saunf:"🌱","mustard seeds":"🌱",rai:"🌱","fenugreek seeds":"🌱","methi seeds":"🌱",
  kalonji:"🌱","nigella seeds":"🌱",
  cardamom:"🫙",elaichi:"🫙",clove:"🫙",laung:"🫙",nutmeg:"🫙",jaiphal:"🫙","star anise":"⭐",
  "coriander powder":"🫙","dhania powder":"🫙",
  "italian seasoning":"🌿","taco seasoning":"🌮","old bay":"🦀",
  bouillon:"🍲","bouillon cube":"🍲",seasoning:"🫙",
  pesto:"🌿","alfredo sauce":"🧀","pasta sauce":"🍝","pizza sauce":"🍕",
  tamarind:"🫙",imli:"🫙",kokum:"🫙",
  // Beverages
  water:"💧","bottled water":"💧","sparkling water":"💧",seltzer:"💧","mineral water":"💧","tonic water":"💧",
  juice:"🧃","orange juice":"🍊","apple juice":"🍎","cranberry juice":"🍒","grape juice":"🍇",lemonade:"🍋","nimbu pani":"🍋","aam panna":"🥭",
  soda:"🥤",cola:"🥤",coke:"🥤",pepsi:"🥤",sprite:"🥤","ginger ale":"🥤","root beer":"🥤",
  coffee:"☕","ground coffee":"☕","coffee beans":"☕","instant coffee":"☕","k-cups":"☕","cold brew":"☕",espresso:"☕",
  tea:"🍵","green tea":"🍵","black tea":"🍵","herbal tea":"🍵",chai:"🍵",matcha:"🍵","iced tea":"🍵","chai patti":"🍵","tea leaves":"🍵",
  beer:"🍺",ipa:"🍺",lager:"🍺",ale:"🍺",stout:"🍺","craft beer":"🍺","hard seltzer":"🍺",
  wine:"🍷","red wine":"🍷","white wine":"🍾",rose:"🍷",champagne:"🍾",prosecco:"🍾",
  liquor:"🥃",vodka:"🍸",whiskey:"🥃",rum:"🥃",tequila:"🥃",gin:"🍸",bourbon:"🥃",
  kombucha:"🍵","coconut water":"🥥","nariyal pani":"🥥",
  "almond milk":"🥛","oat milk":"🥛","soy milk":"🥛","plant milk":"🥛",
  "energy drink":"⚡","red bull":"⚡",monster:"⚡",gatorade:"⚡","sports drink":"⚡",electrolyte:"⚡",
  "hot chocolate":"🍫","cocoa mix":"🍫","rooh afza":"🌹",sharbat:"🌹",jaljeera:"🍋",
  // Household
  "paper towel":"🧻","paper towels":"🧻",napkins:"🧻",tissue:"🧻",tissues:"🧻","facial tissue":"🧻",kleenex:"🧻",
  "toilet paper":"🧻","bath tissue":"🧻",
  "trash bag":"🗑️","trash bags":"🗑️","garbage bags":"🗑️","bin liners":"🗑️",
  "dish soap":"🧴","dishwashing liquid":"🧴",dawn:"🧴",
  detergent:"🧺","laundry detergent":"🧺",tide:"🧺","fabric softener":"🧺","dryer sheets":"🧺",
  bleach:"🧹",disinfectant:"🧹",lysol:"🧹",clorox:"🧹",
  "all purpose cleaner":"🧹","glass cleaner":"🧹",windex:"🧹","surface cleaner":"🧹",
  sponge:"🧽",sponges:"🧽","scrub brush":"🧽","steel wool":"🧽",
  candle:"🕯️",candles:"🕯️","air freshener":"🌸",febreze:"🌸",agarbatti:"🪔",incense:"🪔",
  "light bulb":"💡","light bulbs":"💡",batteries:"🔋",battery:"🔋",
  matches:"🔥",lighter:"🔥","hand sanitizer":"🧴",
  // Health & Beauty
  "body wash":"🚿","shower gel":"🚿",shampoo:"🧴",conditioner:"🧴","hair gel":"🧴",
  soap:"🧼","bar soap":"🧼","hand soap":"🧼","liquid soap":"🧼",
  toothpaste:"🪥",toothbrush:"🪥",floss:"🦷","dental floss":"🦷",mouthwash:"🦷",listerine:"🦷",
  deodorant:"🧴",antiperspirant:"🧴",
  lotion:"🧴","body lotion":"🧴","hand cream":"🧴",moisturizer:"🧴","face cream":"🧴","face wash":"🧴",
  sunscreen:"☀️",sunblock:"☀️",
  razor:"🪒",razors:"🪒","shaving cream":"🪒",
  "band-aid":"🩹",bandaid:"🩹",bandage:"🩹",gauze:"🩹","first aid":"🩹",
  medicine:"💊",ibuprofen:"💊",tylenol:"💊",advil:"💊",aspirin:"💊",
  allergy:"💊",benadryl:"💊",claritin:"💊",zyrtec:"💊",
  "cold medicine":"💊",dayquil:"💊",nyquil:"💊","cough syrup":"💊","cough drops":"💊",
  antacid:"💊",tums:"💊",pepto:"💊",eno:"💊",
  vitamin:"💊",vitamins:"💊",multivitamin:"💊","vitamin d":"💊","vitamin c":"💊","fish oil":"💊",probiotic:"💊",supplement:"💊",
  "eye drops":"👁️","contact lens":"👁️","contact solution":"👁️",
  "cotton balls":"⚪","cotton pads":"⚪","q-tips":"⚪",
  makeup:"💄",mascara:"💄",foundation:"💄",lipstick:"💄","lip balm":"💋",chapstick:"💋",
  // Baby & Kids
  diapers:"👶",diaper:"👶",nappy:"👶",nappies:"👶","pull-ups":"👶",
  wipes:"🧻","baby wipes":"🧻","wet wipes":"🧻",
  formula:"🍼","baby formula":"🍼",similac:"🍼",enfamil:"🍼",
  "baby food":"🍼","baby cereal":"🍼",cerelac:"🍼",
  "sippy cup":"🥤","baby bottle":"🍼",pacifier:"👶",
  "baby wash":"🧴","baby shampoo":"🧴","baby lotion":"🧴","baby oil":"🧴","baby powder":"👶","diaper cream":"🧴",
  "juice box":"🧃","juice boxes":"🧃",lunchable:"🍱",lunchables:"🍱",
  "fruit pouch":"🍎","squeeze pouch":"🍎","snack pack":"🍪",
  // Pet
  "dog food":"🐕","cat food":"🐈","pet food":"🐾",kibble:"🐾",
  "dog treats":"🦴","cat treats":"🐈","pet treats":"🐾",
  "cat litter":"🐈","kitty litter":"🐈",litter:"🐈",
  "pet shampoo":"🐾",flea:"🐾",tick:"🐾",
  "chew toy":"🦴","dog toy":"🐕","cat toy":"🐈","pet toy":"🐾",
  leash:"🐕",collar:"🐕",harness:"🐕","bird seed":"🐦",birdseed:"🐦","fish food":"🐠",
  "puppy pad":"🐕","puppy pads":"🐕",
};

export function detectItemIcon(text) {
  const lower = text.toLowerCase().trim();
  if (ITEM_ICONS[lower]) return ITEM_ICONS[lower];
  let best = null, bestLen = 0;
  for (const kw in ITEM_ICONS) {
    if ((lower.includes(kw) || kw.includes(lower)) && kw.length > bestLen) { best = ITEM_ICONS[kw]; bestLen = kw.length; }
  }
  return best;
}
